name: Goodman Family Cookbook
markdown: kramdown
collections:
  about:
    output: true
  appetizers:
    output: true
  soups_and_salads:
    output: true
  sides:
    output: true
  meats:
    output: true
  poultry:
    output: true
