name: Goodman Family Cookbook
url: "https://gfamcookbook.com"
markdown: kramdown
collections:
  about:
    output: true
  appetizers:
    output: true
  soups_and_salads:
    output: true
  sides:
    output: true
  meats:
    output: true
  poultry:
    output: true
  fish_and_seafood:
    output: true
  pastas:
    output: true
  breads:
    output: true
  mexican:
    output: true
  casseroles:
    output: true
  desserts:
    output: true
